{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggedit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggedit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggedit/ggedit_{{ version }}.tar.gz
  sha256: ffc9533da64098a262cb9ad18ccba70b92e15fc440e4779e02d41a84d76707ec

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-colourpicker >=0.2
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.0.0
    - r-magrittr
    - r-miniui
    - r-plyr
    - r-purrr
    - r-rlang
    - r-rstudioapi
    - r-scales
    - r-shiny
    - r-shinyace
    - r-shinybs
    - r-tidyr
  run:
    - r-base
    - r-colourpicker >=0.2
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.0.0
    - r-magrittr
    - r-miniui
    - r-plyr
    - r-purrr
    - r-rlang
    - r-rstudioapi
    - r-scales
    - r-shiny
    - r-shinyace
    - r-shinybs
    - r-tidyr

test:
  commands:
    - $R -e "library('ggedit')"           # [not win]
    - "\"%R%\" -e \"library('ggedit')\""  # [win]

about:
  home: https://github.com/yonicd/ggedit
  license: MIT
  summary: Interactively edit 'ggplot2' layer and theme aesthetics definitions.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggedit
# Type: Package
# Title: Interactive 'ggplot2' Layer and Theme Aesthetic Editor
# Version: 0.3.1
# Date: 2020-06-01
# Author: Jonathan Sidi [aut, cre]
# Maintainer: Jonathan Sidi <yonicd@gmail.com>
# Description: Interactively edit 'ggplot2' layer and theme aesthetics definitions.
# Depends: R (>= 3.2.0), ggplot2 (>= 3.0.0)
# Imports: dplyr (>= 1.0.0), plyr, tidyr, purrr, rlang, scales, rstudioapi, shiny, miniUI, shinyBS, colourpicker (>= 0.2), shinyAce, magrittr, utils, graphics, grid, tools, stats
# Suggests: testthat, covr
# License: MIT + file LICENSE
# URL: https://github.com/yonicd/ggedit
# BugReports: https://github.com/yonicd/ggedit/issues
# LazyData: true
# NeedsCompilation: no
# Packaged: 2020-06-02 10:36:39 UTC; yonis
# RoxygenNote: 7.1.0
# Repository: CRAN
# Date/Publication: 2020-06-02 11:50:06 UTC
