appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RDlQCCNyJy2IyjH3Z4fE5H36ukW0o7mQysuwS6j5bsueIXIq7kajhjhUcua3JJtKY08CaIBI1Cc4VCZYzP44SLwkHMtUfOFD6vb4xiMeJVGl9MtvLF1gFY87C0xGNZag3X7iYTMqFaqr2wO+jJZhAUVXN8o3UO0UllbxaqSxNi7ng32oDIGUogh8wDrY4a/5xDfeljqH/geqUANi9/DbtubXeT6heBivQ3beVHqUtjgaqylCZNtUCBd+NylMiSOIuwvGtu8OE6rpcFJwHx1jgyGnbMP6V9VcXbFoRT7AuwTkGCdqcQXVdIXLFcygrebVTxdJ2jhibc2jILlhZBNRN8/cpS0JlpiBHZTS9UMD/CS7UrUBBGsPog9uMZGMG3WyL8G2TZQ3asEvowiHv1zJ0H9UDxKF6HiC0mQPlvq+cXNgdUiGGzTL2XpULQIOyuNV+6TL6sLpJseL/Zzt6LTpmXkc4FWgITl4jB9dS4NANl6Z3dV1RH79ZzElNXDn1pFPn8CYgjt/UdKS7OpjByAs7LzIVcg3dTaaZXde+GN5IbnQyBFyvqzHZ/8Vxt6pWrO5O4Dt+EKByJiHPg4B9mG2mRGEq6rQOu7nyb1cMdfX0Y98mZjGwxYjbPB7BgL8q7WEBvTkjAwa+jHYBwUrreQiwCmzLqtSFkVrksHVcmrBa0A=}
